name: app-mne-bids-sensor-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - numpy<2.0.0
      - spicy
      - matplotlib
      - scikit-learn
      - mne
      - mne-bids
      - mne-bids-pipeline==1.10.1